bt2: Sync native_bt_field_class.i with field-class-const.h
Commit

    2d97b62eea05 ("lib: have dedicated, unique unsigned and signed enum FC mapping objects")

Changed some declarations in field-class-const.h without doing the
corresponding changes in native_bt_field_class.i.  I am now seeing this
build error:

    bt2/native_bt_wrap.c: In function ‘_wrap_field_class_unsigned_enumeration_borrow_mapping_by_index_const’:
    bt2/native_bt_wrap.c:11087:3: error: unknown type name ‘bt_field_class_unsigned_enumeration_mapping_ranges’; did you mean ‘bt_field_class_unsigned_enumeration_mapping’?
       bt_field_class_unsigned_enumeration_mapping_ranges **arg4 = (bt_field_class_unsigned_enumeration_mapping_ranges **) 0 ;
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       bt_field_class_unsigned_enumeration_mapping

Change-Id: I897749a6a7fe5bd1c3c16b1ea9625820e77f112b
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>