Fix: unused-variable warnings in lib/graph/iterator.c
GCC warnings:
  make[3]: Entering directory '/home/frdeso/projets/babeltrace/optimalize/lib/graph'
    CC       iterator.lo
  iterator.c: In function ‘_set_iterator_state_after_seeking’:
  iterator.c:889:59: error: variable ‘new_state’ set but not used [-Werror=unused-but-set-variable]
    enum bt_self_component_port_input_message_iterator_state new_state = 0;
                                                             ^~~~~~~~~
  iterator.c: In function ‘find_message_ge_ns_from_origin’:
  iterator.c:1159:59: error: unused variable ‘init_state’ [-Werror=unused-variable]
    enum bt_self_component_port_input_message_iterator_state init_state =

Signed-off-by: Francis Deslauriers <francis.deslauriers@efficios.com>
Change-Id: Ia14a89f330198e4109af14f755aeed3378912256
Reviewed-on: https://review.lttng.org/c/babeltrace/+/1030
Reviewed-by: Philippe Proulx <eeppeliteloop@gmail.com>